addSbtPlugin("de.gccc.sbt"        % "sbt-jib"                  % "1.3.6")
addSbtPlugin("com.github.sbt"     % "sbt-dynver"               % "5.0.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.13.1")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.10.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.0")
