addSbtPlugin("de.gccc.sbt"        % "sbt-jib"                  % "1.0.1")
addSbtPlugin("com.dwijnand"       % "sbt-dynver"               % "4.1.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.11.0")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.9.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.6")
